packageName: Quali.Torque.Api
useNewtonsoft: false
buildTarget: library
isLibrary: true
apiTests: false
modelTests: false
apis: false
supportingFiles: false
generateBody: false
classModifier: abstract
operationIsAsync: true
