/*
 * Torque API Reference
 *
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Quali.Torque.Api.Converters;

namespace Quali.Torque.Api.Models
{ 
    /// <summary>
    /// Application instance information
    /// </summary>
    [DataContract]
    public class AppInstanceResponse : IEquatable<AppInstanceResponse>
    {
        /// <summary>
        /// Application instance status (\&quot;deploying\&quot;, \&quot;pending\&quot;, \&quot;done\&quot;, etc.)
        /// </summary>
        /// <value>Application instance status (\&quot;deploying\&quot;, \&quot;pending\&quot;, \&quot;done\&quot;, etc.)</value>
        [DataMember(Name="status", EmitDefaultValue=true)]
        public string Status { get; set; }

        /// <summary>
        /// Infra ID of application instance
        /// </summary>
        /// <value>Infra ID of application instance</value>
        [DataMember(Name="infra_id", EmitDefaultValue=true)]
        public string InfraId { get; set; }

        /// <summary>
        /// EC2 instance type
        /// </summary>
        /// <value>EC2 instance type</value>
        [DataMember(Name="instance_type", EmitDefaultValue=true)]
        public string InstanceType { get; set; }

        /// <summary>
        /// RAM limitation for Kubernetes VM
        /// </summary>
        /// <value>RAM limitation for Kubernetes VM</value>
        [DataMember(Name="memory_limit", EmitDefaultValue=true)]
        public string MemoryLimit { get; set; }

        /// <summary>
        /// CPU limitation for Kubernetes VM
        /// </summary>
        /// <value>CPU limitation for Kubernetes VM</value>
        [DataMember(Name="cpu_limit", EmitDefaultValue=true)]
        public string CpuLimit { get; set; }

        /// <summary>
        /// Gets or Sets AccessLinks
        /// </summary>
        [DataMember(Name="access_links", EmitDefaultValue=true)]
        public List<ConnectLinkResponse> AccessLinks { get; set; }

        /// <summary>
        /// Application instance private IP
        /// </summary>
        /// <value>Application instance private IP</value>
        [DataMember(Name="private_ip", EmitDefaultValue=true)]
        public string PrivateIp { get; set; }

        /// <summary>
        /// Gets or Sets ComputeAvailability
        /// </summary>
        [DataMember(Name="compute_availability", EmitDefaultValue=false)]
        public ComputeAvailability ComputeAvailability { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name="links", EmitDefaultValue=true)]
        public List<Hyperlink> Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AppInstanceResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  InfraId: ").Append(InfraId).Append("\n");
            sb.Append("  InstanceType: ").Append(InstanceType).Append("\n");
            sb.Append("  MemoryLimit: ").Append(MemoryLimit).Append("\n");
            sb.Append("  CpuLimit: ").Append(CpuLimit).Append("\n");
            sb.Append("  AccessLinks: ").Append(AccessLinks).Append("\n");
            sb.Append("  PrivateIp: ").Append(PrivateIp).Append("\n");
            sb.Append("  ComputeAvailability: ").Append(ComputeAvailability).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AppInstanceResponse)obj);
        }

        /// <summary>
        /// Returns true if AppInstanceResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of AppInstanceResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AppInstanceResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    InfraId == other.InfraId ||
                    InfraId != null &&
                    InfraId.Equals(other.InfraId)
                ) && 
                (
                    InstanceType == other.InstanceType ||
                    InstanceType != null &&
                    InstanceType.Equals(other.InstanceType)
                ) && 
                (
                    MemoryLimit == other.MemoryLimit ||
                    MemoryLimit != null &&
                    MemoryLimit.Equals(other.MemoryLimit)
                ) && 
                (
                    CpuLimit == other.CpuLimit ||
                    CpuLimit != null &&
                    CpuLimit.Equals(other.CpuLimit)
                ) && 
                (
                    AccessLinks == other.AccessLinks ||
                    AccessLinks != null &&
                    other.AccessLinks != null &&
                    AccessLinks.SequenceEqual(other.AccessLinks)
                ) && 
                (
                    PrivateIp == other.PrivateIp ||
                    PrivateIp != null &&
                    PrivateIp.Equals(other.PrivateIp)
                ) && 
                (
                    ComputeAvailability == other.ComputeAvailability ||
                    
                    ComputeAvailability.Equals(other.ComputeAvailability)
                ) && 
                (
                    Links == other.Links ||
                    Links != null &&
                    other.Links != null &&
                    Links.SequenceEqual(other.Links)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (InfraId != null)
                    hashCode = hashCode * 59 + InfraId.GetHashCode();
                    if (InstanceType != null)
                    hashCode = hashCode * 59 + InstanceType.GetHashCode();
                    if (MemoryLimit != null)
                    hashCode = hashCode * 59 + MemoryLimit.GetHashCode();
                    if (CpuLimit != null)
                    hashCode = hashCode * 59 + CpuLimit.GetHashCode();
                    if (AccessLinks != null)
                    hashCode = hashCode * 59 + AccessLinks.GetHashCode();
                    if (PrivateIp != null)
                    hashCode = hashCode * 59 + PrivateIp.GetHashCode();
                    
                    hashCode = hashCode * 59 + ComputeAvailability.GetHashCode();
                    if (Links != null)
                    hashCode = hashCode * 59 + Links.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AppInstanceResponse left, AppInstanceResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AppInstanceResponse left, AppInstanceResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
