/*
 * Torque API Reference
 *
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Quali.Torque.Api.Converters;

namespace Quali.Torque.Api.Models
{ 
    /// <summary>
    /// Request to launch a new sandbox
    /// </summary>
    [DataContract]
    public class CreateSandboxRequest : IEquatable<CreateSandboxRequest>
    {
        /// <summary>
        /// Sandbox name
        /// </summary>
        /// <value>Sandbox name</value>
        [DataMember(Name="sandbox_name", EmitDefaultValue=true)]
        public string SandboxName { get; set; }

        /// <summary>
        /// Sandbox blueprint name
        /// </summary>
        /// <value>Sandbox blueprint name</value>
        [DataMember(Name="blueprint_name", EmitDefaultValue=true)]
        public string BlueprintName { get; set; }

        /// <summary>
        /// Sandbox description
        /// </summary>
        /// <value>Sandbox description</value>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string Description { get; set; }

        /// <summary>
        /// Launch sandbox integrated pipeline tool in the space (Jenkins, Bitbucket, GitLab, etc.)
        /// </summary>
        /// <value>Launch sandbox integrated pipeline tool in the space (Jenkins, Bitbucket, GitLab, etc.)</value>
        [DataMember(Name="automation", EmitDefaultValue=false)]
        public bool Automation { get; set; }

        /// <summary>
        /// Sandbox scheduled end time in ISO 8601 format  &lt;example&gt;For example, 2021-10-06T08:27:05.215Z.&lt;/example&gt;&lt;remarks&gt;  Cannot have both \&quot;duration\&quot; and \&quot;scheduled_end_time\&quot; specified  &lt;/remarks&gt;
        /// </summary>
        /// <value>Sandbox scheduled end time in ISO 8601 format  &lt;example&gt;For example, 2021-10-06T08:27:05.215Z.&lt;/example&gt;&lt;remarks&gt;  Cannot have both \&quot;duration\&quot; and \&quot;scheduled_end_time\&quot; specified  &lt;/remarks&gt;</value>
        [DataMember(Name="scheduled_end_time", EmitDefaultValue=true)]
        public DateTime? ScheduledEndTime { get; set; }

        /// <summary>
        /// Sandbox duration time in ISO 8601 format: \&quot;P{days}DT{hours}H{minutes}M{seconds}S]]\&quot;  &lt;example&gt;For example, P0DT2H3M4S.&lt;/example&gt;&lt;remarks&gt;  Cannot have both \&quot;duration\&quot; and \&quot;scheduled_end_time\&quot; specified  &lt;/remarks&gt;
        /// </summary>
        /// <value>Sandbox duration time in ISO 8601 format: \&quot;P{days}DT{hours}H{minutes}M{seconds}S]]\&quot;  &lt;example&gt;For example, P0DT2H3M4S.&lt;/example&gt;&lt;remarks&gt;  Cannot have both \&quot;duration\&quot; and \&quot;scheduled_end_time\&quot; specified  &lt;/remarks&gt;</value>
        [DataMember(Name="duration", EmitDefaultValue=true)]
        public string Duration { get; set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name="source", EmitDefaultValue=false)]
        public BlueprintSourceRequest Source { get; set; }

        /// <summary>
        /// Indicates if the sandbox is hidden or visible  &lt;remarks&gt;  - \&quot;normal\&quot;: sandbox is visible  - \&quot;hidden\&quot;: sandbox is hidden  &lt;/remarks&gt;
        /// </summary>
        /// <value>Indicates if the sandbox is hidden or visible  &lt;remarks&gt;  - \&quot;normal\&quot;: sandbox is visible  - \&quot;hidden\&quot;: sandbox is hidden  &lt;/remarks&gt;</value>
        [DataMember(Name="visibility", EmitDefaultValue=true)]
        public string Visibility { get; set; }

        /// <summary>
        /// Artifact files required by the applications of the blueprint  &lt;remarks&gt;  For each application, specify the application name and artifact file path (path is relative to the repo name defined in the space).  &lt;/remarks&gt;
        /// </summary>
        /// <value>Artifact files required by the applications of the blueprint  &lt;remarks&gt;  For each application, specify the application name and artifact file path (path is relative to the repo name defined in the space).  &lt;/remarks&gt;</value>
        [DataMember(Name="artifacts", EmitDefaultValue=true)]
        public Dictionary<string, string> Artifacts { get; set; }

        /// <summary>
        /// Environment blueprint inputs
        /// </summary>
        /// <value>Environment blueprint inputs</value>
        [DataMember(Name="inputs", EmitDefaultValue=true)]
        public Dictionary<string, string> Inputs { get; set; }

        /// <summary>
        /// Environment blueprint tags
        /// </summary>
        /// <value>Environment blueprint tags</value>
        [DataMember(Name="tags", EmitDefaultValue=true)]
        public Dictionary<string, string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets ComputeAvailability
        /// </summary>
        [DataMember(Name="compute_availability", EmitDefaultValue=false)]
        public ComputeAvailability ComputeAvailability { get; set; }

        /// <summary>
        /// Set to \&quot;true\&quot; to allow the sandbox to launch without verifying the existence of the artifacts of the sandbox
        /// </summary>
        /// <value>Set to \&quot;true\&quot; to allow the sandbox to launch without verifying the existence of the artifacts of the sandbox</value>
        [DataMember(Name="lazy_load_artifacts", EmitDefaultValue=true)]
        public bool? LazyLoadArtifacts { get; set; }

        /// <summary>
        /// Time to wait (in minutes) for artifacts before setup fails
        /// </summary>
        /// <value>Time to wait (in minutes) for artifacts before setup fails</value>
        [DataMember(Name="lazy_load_artifacts_timeout", EmitDefaultValue=true)]
        public int? LazyLoadArtifactsTimeout { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateSandboxRequest {\n");
            sb.Append("  SandboxName: ").Append(SandboxName).Append("\n");
            sb.Append("  BlueprintName: ").Append(BlueprintName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Automation: ").Append(Automation).Append("\n");
            sb.Append("  ScheduledEndTime: ").Append(ScheduledEndTime).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Visibility: ").Append(Visibility).Append("\n");
            sb.Append("  Artifacts: ").Append(Artifacts).Append("\n");
            sb.Append("  Inputs: ").Append(Inputs).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  ComputeAvailability: ").Append(ComputeAvailability).Append("\n");
            sb.Append("  LazyLoadArtifacts: ").Append(LazyLoadArtifacts).Append("\n");
            sb.Append("  LazyLoadArtifactsTimeout: ").Append(LazyLoadArtifactsTimeout).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateSandboxRequest)obj);
        }

        /// <summary>
        /// Returns true if CreateSandboxRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateSandboxRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateSandboxRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    SandboxName == other.SandboxName ||
                    SandboxName != null &&
                    SandboxName.Equals(other.SandboxName)
                ) && 
                (
                    BlueprintName == other.BlueprintName ||
                    BlueprintName != null &&
                    BlueprintName.Equals(other.BlueprintName)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    Automation == other.Automation ||
                    
                    Automation.Equals(other.Automation)
                ) && 
                (
                    ScheduledEndTime == other.ScheduledEndTime ||
                    ScheduledEndTime != null &&
                    ScheduledEndTime.Equals(other.ScheduledEndTime)
                ) && 
                (
                    Duration == other.Duration ||
                    Duration != null &&
                    Duration.Equals(other.Duration)
                ) && 
                (
                    Source == other.Source ||
                    Source != null &&
                    Source.Equals(other.Source)
                ) && 
                (
                    Visibility == other.Visibility ||
                    Visibility != null &&
                    Visibility.Equals(other.Visibility)
                ) && 
                (
                    Artifacts == other.Artifacts ||
                    Artifacts != null &&
                    other.Artifacts != null &&
                    Artifacts.SequenceEqual(other.Artifacts)
                ) && 
                (
                    Inputs == other.Inputs ||
                    Inputs != null &&
                    other.Inputs != null &&
                    Inputs.SequenceEqual(other.Inputs)
                ) && 
                (
                    Tags == other.Tags ||
                    Tags != null &&
                    other.Tags != null &&
                    Tags.SequenceEqual(other.Tags)
                ) && 
                (
                    ComputeAvailability == other.ComputeAvailability ||
                    
                    ComputeAvailability.Equals(other.ComputeAvailability)
                ) && 
                (
                    LazyLoadArtifacts == other.LazyLoadArtifacts ||
                    LazyLoadArtifacts != null &&
                    LazyLoadArtifacts.Equals(other.LazyLoadArtifacts)
                ) && 
                (
                    LazyLoadArtifactsTimeout == other.LazyLoadArtifactsTimeout ||
                    LazyLoadArtifactsTimeout != null &&
                    LazyLoadArtifactsTimeout.Equals(other.LazyLoadArtifactsTimeout)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (SandboxName != null)
                    hashCode = hashCode * 59 + SandboxName.GetHashCode();
                    if (BlueprintName != null)
                    hashCode = hashCode * 59 + BlueprintName.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    
                    hashCode = hashCode * 59 + Automation.GetHashCode();
                    if (ScheduledEndTime != null)
                    hashCode = hashCode * 59 + ScheduledEndTime.GetHashCode();
                    if (Duration != null)
                    hashCode = hashCode * 59 + Duration.GetHashCode();
                    if (Source != null)
                    hashCode = hashCode * 59 + Source.GetHashCode();
                    if (Visibility != null)
                    hashCode = hashCode * 59 + Visibility.GetHashCode();
                    if (Artifacts != null)
                    hashCode = hashCode * 59 + Artifacts.GetHashCode();
                    if (Inputs != null)
                    hashCode = hashCode * 59 + Inputs.GetHashCode();
                    if (Tags != null)
                    hashCode = hashCode * 59 + Tags.GetHashCode();
                    
                    hashCode = hashCode * 59 + ComputeAvailability.GetHashCode();
                    if (LazyLoadArtifacts != null)
                    hashCode = hashCode * 59 + LazyLoadArtifacts.GetHashCode();
                    if (LazyLoadArtifactsTimeout != null)
                    hashCode = hashCode * 59 + LazyLoadArtifactsTimeout.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateSandboxRequest left, CreateSandboxRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateSandboxRequest left, CreateSandboxRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
