/*
 * Torque API Reference
 *
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Quali.Torque.Api.Converters;

namespace Quali.Torque.Api.Models
{ 
    /// <summary>
    /// Environment cost information
    /// </summary>
    [DataContract]
    public class EnvCost : IEquatable<EnvCost>
    {
        /// <summary>
        /// Total cost sum
        /// </summary>
        /// <value>Total cost sum</value>
        [DataMember(Name="sum", EmitDefaultValue=false)]
        public double Sum { get; set; }

        /// <summary>
        /// Time of the last update of environment cost
        /// </summary>
        /// <value>Time of the last update of environment cost</value>
        [DataMember(Name="last_update", EmitDefaultValue=false)]
        public DateTime LastUpdate { get; set; }

        /// <summary>
        /// Is the cost final
        /// </summary>
        /// <value>Is the cost final</value>
        [DataMember(Name="final", EmitDefaultValue=false)]
        public bool Final { get; set; }

        /// <summary>
        /// Currency code in ISO 4217 format (3 letters like USD, EUR, GBP etc.)
        /// </summary>
        /// <value>Currency code in ISO 4217 format (3 letters like USD, EUR, GBP etc.)</value>
        [DataMember(Name="currency", EmitDefaultValue=true)]
        public string Currency { get; set; }

        /// <summary>
        /// Is the cost incomplete
        /// </summary>
        /// <value>Is the cost incomplete</value>
        [DataMember(Name="incomplete", EmitDefaultValue=false)]
        public bool Incomplete { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EnvCost {\n");
            sb.Append("  Sum: ").Append(Sum).Append("\n");
            sb.Append("  LastUpdate: ").Append(LastUpdate).Append("\n");
            sb.Append("  Final: ").Append(Final).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Incomplete: ").Append(Incomplete).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((EnvCost)obj);
        }

        /// <summary>
        /// Returns true if EnvCost instances are equal
        /// </summary>
        /// <param name="other">Instance of EnvCost to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EnvCost other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Sum == other.Sum ||
                    
                    Sum.Equals(other.Sum)
                ) && 
                (
                    LastUpdate == other.LastUpdate ||
                    LastUpdate != null &&
                    LastUpdate.Equals(other.LastUpdate)
                ) && 
                (
                    Final == other.Final ||
                    
                    Final.Equals(other.Final)
                ) && 
                (
                    Currency == other.Currency ||
                    Currency != null &&
                    Currency.Equals(other.Currency)
                ) && 
                (
                    Incomplete == other.Incomplete ||
                    
                    Incomplete.Equals(other.Incomplete)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Sum.GetHashCode();
                    if (LastUpdate != null)
                    hashCode = hashCode * 59 + LastUpdate.GetHashCode();
                    
                    hashCode = hashCode * 59 + Final.GetHashCode();
                    if (Currency != null)
                    hashCode = hashCode * 59 + Currency.GetHashCode();
                    
                    hashCode = hashCode * 59 + Incomplete.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(EnvCost left, EnvCost right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(EnvCost left, EnvCost right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
