/*
 * Torque API Reference
 *
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Quali.Torque.Api.Converters;

namespace Quali.Torque.Api.Models
{ 
    /// <summary>
    /// Launching progress step details
    /// </summary>
    [DataContract]
    public class LaunchingProgressStepResponse : IEquatable<LaunchingProgressStepResponse>
    {
        /// <summary>
        /// Launching progress status (\&quot;pending\&quot;, \&quot;in progress\&quot;, \&quot;done\&quot;, etc.)
        /// </summary>
        /// <value>Launching progress status (\&quot;pending\&quot;, \&quot;in progress\&quot;, \&quot;done\&quot;, etc.)</value>
        [DataMember(Name="status", EmitDefaultValue=true)]
        public string Status { get; set; }

        /// <summary>
        /// Total of items to be launched
        /// </summary>
        /// <value>Total of items to be launched</value>
        [DataMember(Name="total", EmitDefaultValue=false)]
        public int Total { get; set; }

        /// <summary>
        /// Total of items that were launched successfully
        /// </summary>
        /// <value>Total of items that were launched successfully</value>
        [DataMember(Name="succeeded", EmitDefaultValue=false)]
        public int Succeeded { get; set; }

        /// <summary>
        /// Total of items that failed to launch
        /// </summary>
        /// <value>Total of items that failed to launch</value>
        [DataMember(Name="failed", EmitDefaultValue=false)]
        public int Failed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LaunchingProgressStepResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Succeeded: ").Append(Succeeded).Append("\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LaunchingProgressStepResponse)obj);
        }

        /// <summary>
        /// Returns true if LaunchingProgressStepResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of LaunchingProgressStepResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LaunchingProgressStepResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    Total == other.Total ||
                    
                    Total.Equals(other.Total)
                ) && 
                (
                    Succeeded == other.Succeeded ||
                    
                    Succeeded.Equals(other.Succeeded)
                ) && 
                (
                    Failed == other.Failed ||
                    
                    Failed.Equals(other.Failed)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    
                    hashCode = hashCode * 59 + Total.GetHashCode();
                    
                    hashCode = hashCode * 59 + Succeeded.GetHashCode();
                    
                    hashCode = hashCode * 59 + Failed.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LaunchingProgressStepResponse left, LaunchingProgressStepResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LaunchingProgressStepResponse left, LaunchingProgressStepResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
