/*
 * Torque API Reference
 *
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Quali.Torque.Api.Converters;

namespace Quali.Torque.Api.Models
{ 
    /// <summary>
    /// Launching progress of an environment information
    /// </summary>
    [DataContract]
    public class LaunchingProgressResponse : IEquatable<LaunchingProgressResponse>
    {
        /// <summary>
        /// Gets or Sets CreatingInfrastructure
        /// </summary>
        [DataMember(Name="creating_infrastructure", EmitDefaultValue=false)]
        public LaunchingProgressStepResponse CreatingInfrastructure { get; set; }

        /// <summary>
        /// Gets or Sets PreparingArtifacts
        /// </summary>
        [DataMember(Name="preparing_artifacts", EmitDefaultValue=false)]
        public LaunchingProgressStepResponse PreparingArtifacts { get; set; }

        /// <summary>
        /// Gets or Sets DeployingApplications
        /// </summary>
        [DataMember(Name="deploying_applications", EmitDefaultValue=false)]
        public LaunchingProgressStepResponse DeployingApplications { get; set; }

        /// <summary>
        /// Gets or Sets VerifyingEnvironment
        /// </summary>
        [DataMember(Name="verifying_environment", EmitDefaultValue=false)]
        public LaunchingProgressStepResponse VerifyingEnvironment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LaunchingProgressResponse {\n");
            sb.Append("  CreatingInfrastructure: ").Append(CreatingInfrastructure).Append("\n");
            sb.Append("  PreparingArtifacts: ").Append(PreparingArtifacts).Append("\n");
            sb.Append("  DeployingApplications: ").Append(DeployingApplications).Append("\n");
            sb.Append("  VerifyingEnvironment: ").Append(VerifyingEnvironment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LaunchingProgressResponse)obj);
        }

        /// <summary>
        /// Returns true if LaunchingProgressResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of LaunchingProgressResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LaunchingProgressResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CreatingInfrastructure == other.CreatingInfrastructure ||
                    CreatingInfrastructure != null &&
                    CreatingInfrastructure.Equals(other.CreatingInfrastructure)
                ) && 
                (
                    PreparingArtifacts == other.PreparingArtifacts ||
                    PreparingArtifacts != null &&
                    PreparingArtifacts.Equals(other.PreparingArtifacts)
                ) && 
                (
                    DeployingApplications == other.DeployingApplications ||
                    DeployingApplications != null &&
                    DeployingApplications.Equals(other.DeployingApplications)
                ) && 
                (
                    VerifyingEnvironment == other.VerifyingEnvironment ||
                    VerifyingEnvironment != null &&
                    VerifyingEnvironment.Equals(other.VerifyingEnvironment)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CreatingInfrastructure != null)
                    hashCode = hashCode * 59 + CreatingInfrastructure.GetHashCode();
                    if (PreparingArtifacts != null)
                    hashCode = hashCode * 59 + PreparingArtifacts.GetHashCode();
                    if (DeployingApplications != null)
                    hashCode = hashCode * 59 + DeployingApplications.GetHashCode();
                    if (VerifyingEnvironment != null)
                    hashCode = hashCode * 59 + VerifyingEnvironment.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LaunchingProgressResponse left, LaunchingProgressResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LaunchingProgressResponse left, LaunchingProgressResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
