/*
 * Torque API Reference
 *
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Quali.Torque.Api.Converters;

namespace Quali.Torque.Api.Models
{ 
    /// <summary>
    /// Production information
    /// </summary>
    [DataContract]
    public class ProductionResponseListItem : IEquatable<ProductionResponseListItem>
    {
        /// <summary>
        /// Production environment ID
        /// </summary>
        /// <value>Production environment ID</value>
        [DataMember(Name="id", EmitDefaultValue=true)]
        public string Id { get; set; }

        /// <summary>
        /// Production environment name
        /// </summary>
        /// <value>Production environment name</value>
        [DataMember(Name="name", EmitDefaultValue=true)]
        public string Name { get; set; }

        /// <summary>
        /// Description of the production environment&#39;s blueprint
        /// </summary>
        /// <value>Description of the production environment&#39;s blueprint</value>
        [DataMember(Name="blueprint_description", EmitDefaultValue=true)]
        public string BlueprintDescription { get; set; }

        /// <summary>
        /// Production environment creation date in ISO 8601 format
        /// </summary>
        /// <value>Production environment creation date in ISO 8601 format</value>
        [DataMember(Name="create_time", EmitDefaultValue=true)]
        public string CreateTime { get; set; }

        /// <summary>
        /// Status of the production environment update process (\&quot;None\&quot;, \&quot;Deploying Green\&quot;, \&quot;Cleaning Up\&quot;, etc.)
        /// </summary>
        /// <value>Status of the production environment update process (\&quot;None\&quot;, \&quot;Deploying Green\&quot;, \&quot;Cleaning Up\&quot;, etc.)</value>
        [DataMember(Name="update_status", EmitDefaultValue=true)]
        public string UpdateStatus { get; set; }

        /// <summary>
        /// Production environment strategy (currently only blue/green is supported)
        /// </summary>
        /// <value>Production environment strategy (currently only blue/green is supported)</value>
        [DataMember(Name="update_strategy", EmitDefaultValue=true)]
        public string UpdateStrategy { get; set; }

        /// <summary>
        /// Blue production environment status
        /// </summary>
        /// <value>Blue production environment status</value>
        [DataMember(Name="blue_status", EmitDefaultValue=true)]
        public string BlueStatus { get; set; }

        /// <summary>
        /// Production environment deployment start time in ISO 8601 format
        /// </summary>
        /// <value>Production environment deployment start time in ISO 8601 format</value>
        [DataMember(Name="deployment_start_time", EmitDefaultValue=true)]
        public string DeploymentStartTime { get; set; }

        /// <summary>
        /// Gets or Sets BlueApplications
        /// </summary>
        [DataMember(Name="blue_applications", EmitDefaultValue=true)]
        public List<ApplicationResponseBase> BlueApplications { get; set; }

        /// <summary>
        /// Green production environment status
        /// </summary>
        /// <value>Green production environment status</value>
        [DataMember(Name="green_status", EmitDefaultValue=true)]
        public string GreenStatus { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name="links", EmitDefaultValue=true)]
        public List<Hyperlink> Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductionResponseListItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  BlueprintDescription: ").Append(BlueprintDescription).Append("\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("  UpdateStatus: ").Append(UpdateStatus).Append("\n");
            sb.Append("  UpdateStrategy: ").Append(UpdateStrategy).Append("\n");
            sb.Append("  BlueStatus: ").Append(BlueStatus).Append("\n");
            sb.Append("  DeploymentStartTime: ").Append(DeploymentStartTime).Append("\n");
            sb.Append("  BlueApplications: ").Append(BlueApplications).Append("\n");
            sb.Append("  GreenStatus: ").Append(GreenStatus).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductionResponseListItem)obj);
        }

        /// <summary>
        /// Returns true if ProductionResponseListItem instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductionResponseListItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductionResponseListItem other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    BlueprintDescription == other.BlueprintDescription ||
                    BlueprintDescription != null &&
                    BlueprintDescription.Equals(other.BlueprintDescription)
                ) && 
                (
                    CreateTime == other.CreateTime ||
                    CreateTime != null &&
                    CreateTime.Equals(other.CreateTime)
                ) && 
                (
                    UpdateStatus == other.UpdateStatus ||
                    UpdateStatus != null &&
                    UpdateStatus.Equals(other.UpdateStatus)
                ) && 
                (
                    UpdateStrategy == other.UpdateStrategy ||
                    UpdateStrategy != null &&
                    UpdateStrategy.Equals(other.UpdateStrategy)
                ) && 
                (
                    BlueStatus == other.BlueStatus ||
                    BlueStatus != null &&
                    BlueStatus.Equals(other.BlueStatus)
                ) && 
                (
                    DeploymentStartTime == other.DeploymentStartTime ||
                    DeploymentStartTime != null &&
                    DeploymentStartTime.Equals(other.DeploymentStartTime)
                ) && 
                (
                    BlueApplications == other.BlueApplications ||
                    BlueApplications != null &&
                    other.BlueApplications != null &&
                    BlueApplications.SequenceEqual(other.BlueApplications)
                ) && 
                (
                    GreenStatus == other.GreenStatus ||
                    GreenStatus != null &&
                    GreenStatus.Equals(other.GreenStatus)
                ) && 
                (
                    Links == other.Links ||
                    Links != null &&
                    other.Links != null &&
                    Links.SequenceEqual(other.Links)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (BlueprintDescription != null)
                    hashCode = hashCode * 59 + BlueprintDescription.GetHashCode();
                    if (CreateTime != null)
                    hashCode = hashCode * 59 + CreateTime.GetHashCode();
                    if (UpdateStatus != null)
                    hashCode = hashCode * 59 + UpdateStatus.GetHashCode();
                    if (UpdateStrategy != null)
                    hashCode = hashCode * 59 + UpdateStrategy.GetHashCode();
                    if (BlueStatus != null)
                    hashCode = hashCode * 59 + BlueStatus.GetHashCode();
                    if (DeploymentStartTime != null)
                    hashCode = hashCode * 59 + DeploymentStartTime.GetHashCode();
                    if (BlueApplications != null)
                    hashCode = hashCode * 59 + BlueApplications.GetHashCode();
                    if (GreenStatus != null)
                    hashCode = hashCode * 59 + GreenStatus.GetHashCode();
                    if (Links != null)
                    hashCode = hashCode * 59 + Links.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductionResponseListItem left, ProductionResponseListItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductionResponseListItem left, ProductionResponseListItem right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
