/*
 * Torque API Reference
 *
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Quali.Torque.Api.Converters;

namespace Quali.Torque.Api.Models
{ 
    /// <summary>
    /// Sandbox network details
    /// </summary>
    [DataContract]
    public class SandboxNetwork : IEquatable<SandboxNetwork>
    {
        /// <summary>
        /// Cloud account region
        /// </summary>
        /// <value>Cloud account region</value>
        [DataMember(Name="region", EmitDefaultValue=true)]
        public string Region { get; set; }

        /// <summary>
        /// Virtual network ID (AWS: VPC ID; Azure: VNet name)
        /// </summary>
        /// <value>Virtual network ID (AWS: VPC ID; Azure: VNet name)</value>
        [DataMember(Name="network_id", EmitDefaultValue=true)]
        public string NetworkId { get; set; }

        /// <summary>
        /// ID of subnet where application gateway is installed
        /// </summary>
        /// <value>ID of subnet where application gateway is installed</value>
        [DataMember(Name="gateway_subnet", EmitDefaultValue=true)]
        public string GatewaySubnet { get; set; }

        /// <summary>
        /// ID of subnet where management infrastructure of sandbox is installed
        /// </summary>
        /// <value>ID of subnet where management infrastructure of sandbox is installed</value>
        [DataMember(Name="management_subnet", EmitDefaultValue=true)]
        public string ManagementSubnet { get; set; }

        /// <summary>
        /// ID of subnet(s) where applications of sandbox are deployed
        /// </summary>
        /// <value>ID of subnet(s) where applications of sandbox are deployed</value>
        [DataMember(Name="application_subnets", EmitDefaultValue=true)]
        public List<string> ApplicationSubnets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SandboxNetwork {\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  NetworkId: ").Append(NetworkId).Append("\n");
            sb.Append("  GatewaySubnet: ").Append(GatewaySubnet).Append("\n");
            sb.Append("  ManagementSubnet: ").Append(ManagementSubnet).Append("\n");
            sb.Append("  ApplicationSubnets: ").Append(ApplicationSubnets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SandboxNetwork)obj);
        }

        /// <summary>
        /// Returns true if SandboxNetwork instances are equal
        /// </summary>
        /// <param name="other">Instance of SandboxNetwork to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SandboxNetwork other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Region == other.Region ||
                    Region != null &&
                    Region.Equals(other.Region)
                ) && 
                (
                    NetworkId == other.NetworkId ||
                    NetworkId != null &&
                    NetworkId.Equals(other.NetworkId)
                ) && 
                (
                    GatewaySubnet == other.GatewaySubnet ||
                    GatewaySubnet != null &&
                    GatewaySubnet.Equals(other.GatewaySubnet)
                ) && 
                (
                    ManagementSubnet == other.ManagementSubnet ||
                    ManagementSubnet != null &&
                    ManagementSubnet.Equals(other.ManagementSubnet)
                ) && 
                (
                    ApplicationSubnets == other.ApplicationSubnets ||
                    ApplicationSubnets != null &&
                    other.ApplicationSubnets != null &&
                    ApplicationSubnets.SequenceEqual(other.ApplicationSubnets)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Region != null)
                    hashCode = hashCode * 59 + Region.GetHashCode();
                    if (NetworkId != null)
                    hashCode = hashCode * 59 + NetworkId.GetHashCode();
                    if (GatewaySubnet != null)
                    hashCode = hashCode * 59 + GatewaySubnet.GetHashCode();
                    if (ManagementSubnet != null)
                    hashCode = hashCode * 59 + ManagementSubnet.GetHashCode();
                    if (ApplicationSubnets != null)
                    hashCode = hashCode * 59 + ApplicationSubnets.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SandboxNetwork left, SandboxNetwork right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SandboxNetwork left, SandboxNetwork right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
