/*
 * Torque API Reference
 *
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Quali.Torque.Api.Converters;

namespace Quali.Torque.Api.Models
{ 
    /// <summary>
    /// Service information
    /// </summary>
    [DataContract]
    public class ServiceResponse : IEquatable<ServiceResponse>
    {
        /// <summary>
        /// Service name
        /// </summary>
        /// <value>Service name</value>
        [DataMember(Name="name", EmitDefaultValue=true)]
        public string Name { get; set; }

        /// <summary>
        /// Status of service (\&quot;Pending\&quot;, \&quot;Aborted\&quot;, \&quot;Done\&quot;, etc.)
        /// </summary>
        /// <value>Status of service (\&quot;Pending\&quot;, \&quot;Aborted\&quot;, \&quot;Done\&quot;, etc.)</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public Object Status { get; set; }

        /// <summary>
        /// Service type (\&quot;All\&quot;, \&quot;Terraform\&quot;, \&quot;Unknown\&quot;, etc.)
        /// </summary>
        /// <value>Service type (\&quot;All\&quot;, \&quot;Terraform\&quot;, \&quot;Unknown\&quot;, etc.)</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public Object Type { get; set; }

        /// <summary>
        /// Service icon
        /// </summary>
        /// <value>Service icon</value>
        [DataMember(Name="icon", EmitDefaultValue=true)]
        public string Icon { get; set; }

        /// <summary>
        /// Gets or Sets Stages
        /// </summary>
        [DataMember(Name="stages", EmitDefaultValue=true)]
        public List<StageResponse> Stages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServiceResponse {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  Stages: ").Append(Stages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ServiceResponse)obj);
        }

        /// <summary>
        /// Returns true if ServiceResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of ServiceResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) && 
                (
                    Icon == other.Icon ||
                    Icon != null &&
                    Icon.Equals(other.Icon)
                ) && 
                (
                    Stages == other.Stages ||
                    Stages != null &&
                    other.Stages != null &&
                    Stages.SequenceEqual(other.Stages)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (Icon != null)
                    hashCode = hashCode * 59 + Icon.GetHashCode();
                    if (Stages != null)
                    hashCode = hashCode * 59 + Stages.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ServiceResponse left, ServiceResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ServiceResponse left, ServiceResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
