/*
 * Torque API Reference
 *
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Quali.Torque.Api.Converters;

namespace Quali.Torque.Api.Models
{ 
    /// <summary>
    /// Tag response
    /// </summary>
    [DataContract]
    public class TagResponse : IEquatable<TagResponse>
    {
        /// <summary>
        /// Tag scope (&#39;account&#39;, &#39;space&#39;, &#39;blueprint&#39; and &#39;runtime&#39;)
        /// </summary>
        /// <value>Tag scope (&#39;account&#39;, &#39;space&#39;, &#39;blueprint&#39; and &#39;runtime&#39;)</value>
        [DataMember(Name="scope", EmitDefaultValue=true)]
        public string Scope { get; set; }

        /// <summary>
        /// Tag possible values  &lt;remarks&gt;Tag value must be one of the possible values&lt;/remarks&gt;
        /// </summary>
        /// <value>Tag possible values  &lt;remarks&gt;Tag value must be one of the possible values&lt;/remarks&gt;</value>
        [DataMember(Name="possible_values", EmitDefaultValue=true)]
        public List<string> PossibleValues { get; set; }

        /// <summary>
        /// Tag description
        /// </summary>
        /// <value>Tag description</value>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets TagType
        /// </summary>
        [DataMember(Name="tag_type", EmitDefaultValue=false)]
        public Object TagType { get; set; }

        /// <summary>
        /// Tag name
        /// </summary>
        /// <value>Tag name</value>
        [DataMember(Name="name", EmitDefaultValue=true)]
        public string Name { get; set; }

        /// <summary>
        /// Tag value
        /// </summary>
        /// <value>Tag value</value>
        [DataMember(Name="value", EmitDefaultValue=true)]
        public string Value { get; set; }

        /// <summary>
        /// Name of the last user who modified the tag
        /// </summary>
        /// <value>Name of the last user who modified the tag</value>
        [DataMember(Name="modified_by", EmitDefaultValue=true)]
        public string ModifiedBy { get; set; }

        /// <summary>
        /// Last modification data and time of the tag
        /// </summary>
        /// <value>Last modification data and time of the tag</value>
        [DataMember(Name="last_modified", EmitDefaultValue=true)]
        public DateTime? LastModified { get; set; }

        /// <summary>
        /// Name of the user who created the tag
        /// </summary>
        /// <value>Name of the user who created the tag</value>
        [DataMember(Name="created_by", EmitDefaultValue=true)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Creation date and time of the tag
        /// </summary>
        /// <value>Creation date and time of the tag</value>
        [DataMember(Name="created_date", EmitDefaultValue=true)]
        public DateTime? CreatedDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TagResponse {\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  PossibleValues: ").Append(PossibleValues).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  TagType: ").Append(TagType).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  ModifiedBy: ").Append(ModifiedBy).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TagResponse)obj);
        }

        /// <summary>
        /// Returns true if TagResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of TagResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TagResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Scope == other.Scope ||
                    Scope != null &&
                    Scope.Equals(other.Scope)
                ) && 
                (
                    PossibleValues == other.PossibleValues ||
                    PossibleValues != null &&
                    other.PossibleValues != null &&
                    PossibleValues.SequenceEqual(other.PossibleValues)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    TagType == other.TagType ||
                    TagType != null &&
                    TagType.Equals(other.TagType)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Value == other.Value ||
                    Value != null &&
                    Value.Equals(other.Value)
                ) && 
                (
                    ModifiedBy == other.ModifiedBy ||
                    ModifiedBy != null &&
                    ModifiedBy.Equals(other.ModifiedBy)
                ) && 
                (
                    LastModified == other.LastModified ||
                    LastModified != null &&
                    LastModified.Equals(other.LastModified)
                ) && 
                (
                    CreatedBy == other.CreatedBy ||
                    CreatedBy != null &&
                    CreatedBy.Equals(other.CreatedBy)
                ) && 
                (
                    CreatedDate == other.CreatedDate ||
                    CreatedDate != null &&
                    CreatedDate.Equals(other.CreatedDate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Scope != null)
                    hashCode = hashCode * 59 + Scope.GetHashCode();
                    if (PossibleValues != null)
                    hashCode = hashCode * 59 + PossibleValues.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (TagType != null)
                    hashCode = hashCode * 59 + TagType.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Value != null)
                    hashCode = hashCode * 59 + Value.GetHashCode();
                    if (ModifiedBy != null)
                    hashCode = hashCode * 59 + ModifiedBy.GetHashCode();
                    if (LastModified != null)
                    hashCode = hashCode * 59 + LastModified.GetHashCode();
                    if (CreatedBy != null)
                    hashCode = hashCode * 59 + CreatedBy.GetHashCode();
                    if (CreatedDate != null)
                    hashCode = hashCode * 59 + CreatedDate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TagResponse left, TagResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TagResponse left, TagResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
