/*
 * Torque API Reference
 *
 * This page contains information about the Torque APIs and how to use it.<br><br>To be able to test the API methods, you will need an access token to be set in the Authorize section.If you got to this page from your Torque account, we already made it available for you, but you can switch to a different token as needed.<br>To get a different token, use the 'Get token' function available under the 'Access Tokens' section. After running the method, copy the access_token you get in the response and set it in the Authorize fieldas 'Bearer access_token'. For example: Bearer fqSWuw72BbUVFn8AbokF77GJ0r5KEn9MiZjLXF8kBwI.<br><br>The API can be accessed with your account endpoint as will be mentioned in the descriptions and examples or using https://qtorque.io as the prefix instead.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Quali.Torque.Api.Attributes;
using Quali.Torque.Api.Models;

namespace Quali.Torque.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class SettingsApiController : ControllerBase
    { 
        /// <summary>
        /// Get AWS cloud provider
        /// </summary>
        /// <remarks>Get AWS cloud provider settings.</remarks>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/api/settings/cloudproviders/aws")]
        [Authorize(Policy = "Bearer")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(AwsCloudProviderSettingsModel))]
        public abstract IActionResult ApiSettingsCloudprovidersAwsGet();

        /// <summary>
        /// Set AWS cloud provider
        /// </summary>
        /// <remarks>Set AWS cloud provider settings.</remarks>
        /// <param name="awsCloudProviderSettingsModel"></param>
        /// <response code="200">Success</response>
        [HttpPut]
        [Route("/api/settings/cloudproviders/aws")]
        [Authorize(Policy = "Bearer")]
        [Consumes("application/json")]
        [ValidateModelState]
        public abstract IActionResult ApiSettingsCloudprovidersAwsPut([FromBody]AwsCloudProviderSettingsModel awsCloudProviderSettingsModel);
    }
}
